version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    links:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:6.5.4
    volumes:
      - ./plugins:/apps
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "5044:5044"
    entrypoint:
      - /apps/docker-entrypoint-ls-plugin.sh

  grafana:
    links:
      - elasticsearch
    image: grafana/grafana:5.4.2
    ports:
      - "3000:3000"

  filebeat:
    links:
      - logstash
    depends_on: 
      - logstash
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./audit:/usr/share/audit
    
