logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /mnt/auditlogs:/mnt/auditlogs/
  ports:
    - "5000:5000"
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  links:
    - elasticsearch
