version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2 
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    links:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:5.2.2
    volumes:
      - /mnt/auditlogs:/mnt/auditlogs/
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"

  grafana:
    links:
      - elasticsearch
    image: grafana/grafana:4.1.2
    ports:
      - "3000:3000"
