version: '2'

services:
  elasticsearch:
    image: elasticsearch:5.1.1-alpine
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    depends_on:
      - elasticsearch
    image: logstash:5.1.1-alpine
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - /mnt/auditlogs:/mnt/auditlogs/
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  grafana:
    depends_on:
      - elasticsearch
    image: grafana/grafana:4.0.2
    ports:
      - "3000:3000"
    links:
      - elasticsearch
